
name: deploy_frontend

on:
  push:
    branches: [ master ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-azure-cli@v1      

      - name: Upload Website Files to Azure Storage
        run: |
          az storage blob upload-batch -d '$web' -s ./build --account-name cloudresumeacgstorage --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
