
name: deploy_frontend

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4    

      - name: Upload Website Files to Azure Storage
        run: |
          az storage blob upload-batch -d '$web' -s ./build --account-name cloudresumeacgstorage --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
